sonar.projectKey=vikki-iam_eks-demo
sonar.organization=vikki-iam

sonar.sources=src
sonar.tests=src/test
sonar.exclusions=src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
